FROM ct2034/vnc-ros-kinetic-full:latest

RUN apt-get update

RUN apt-get install git

RUN git clone https://github.com/agrobot-tx/agrobot.git

# Move files to appropriate directory
RUN mv agrobot/docker/docker_home/catkin_ws .
RUN mv agrobot/docker/docker_home/map.pgm .
RUN mv agrobot/docker/docker_home/map.yaml .
RUN mv agrobot/docker/docker_home/.gazebo/ ./.gazebo/

# install packages
RUN apt-get install -y ros-kinetic-ros-controllers ros-kinetic-gazebo* ros-kinetic-moveit* ros-kinetic-industrial-core

RUN apt-get install -y ros-kinetic-joy ros-kinetic-teleop-twist-joy ros-kinetic-teleop-twist-keyboard ros-kinetic-laser-proc ros-kinetic-rgbd-launch ros-kinetic-depthimage-to-laserscan ros-kinetic-rosserial-arduino ros-kinetic-rosserial-python ros-kinetic-rosserial-server ros-kinetic-rosserial-client ros-kinetic-rosserial-msgs ros-kinetic-amcl ros-kinetic-map-server ros-kinetic-move-base ros-kinetic-urdf ros-kinetic-xacro ros-kinetic-compressed-image-transport ros-kinetic-rqt-image-view ros-kinetic-gmapping ros-kinetic-navigation ros-kinetic-interactive-markers

RUN apt install -y ros-kinetic-moveit

# Run catkin_make
RUN /bin/bash -c '. /opt/ros/kinetic/setup.bash; cd catkin_ws; catkin_make'

# add variables to bash
RUN /bin/bash -c 'echo "export TURTLEBOT3_MODEL=waffle_pi" >> /root/.bashrc'

RUN /bin/bash -c 'echo "source catkin_ws/devel/setup.bash" >> /root/.bashrc'

COPY kinetic.png /usr/share/doro-lxde-wallpapers



